baseURL = 'https://ais.technosemiotics.eu/'
languageCode = 'en-us'
title = 'ai systems'
theme = 'hugo-book'
enableGitInfo = true

[params]
  BookTheme = 'auto'
  BookToC = true
  BookDateFormat = 'January 2, 2006'
  BookPortableLinks = true
